django/call_app/urls.py
from django.urls import path

from . import views

app_name = 'call_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('deal_result', views.deal_result, name='deal_result'),
    path('webhook_input', views.webhook_input, name='webhook_input'),
    path('calls', views.calls, name='calls'),
]

django/call_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('call_app.urls')),
    path('admin/', admin.site.urls),
]

django/call_app/models.py
from django.db import models


class Crmaccount(models.Model):
    host = models.CharField(max_length=200, verbose_name='host')
    token = models.CharField(max_length=200, verbose_name='token')


class Customer(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя', default="Друг")
    surname = models.CharField(max_length=50, verbose_name='Фамилия', default="Junior")

    def __str__(self):
        return self.name + " " + self.surname


class Call(models.Model):
    deal_id_megaplan = models.CharField(max_length=50, verbose_name='Сделка')
    tipe_of_deal = models.CharField(max_length=50, verbose_name='Тип сделки')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True)
    employee = models.CharField(max_length=50, verbose_name='Сотрудник')
    employee_number = models.CharField(max_length=50, verbose_name='Номер сотрудника',
                                       default="Номер скрыт")
    customer_number = models.CharField(max_length=50, verbose_name='Номер клиента',
                                       default="Номер скрыт")
    call_len = models.CharField(max_length=50,
                                verbose_name='Длительность разговора', default='пока нет данных атс')
    result = models.CharField(max_length=50,
                              verbose_name='Результат звонка', default='пока нет данных атс')
    in_crm = models.CharField(max_length=25,
                              verbose_name=' Добавлено в CRM', default='пока нет данных атс')

django/call_app/forms.py
from django import forms
from .models import Crmaccount


class CrmaccountForm(forms.ModelForm):

    class Meta:
        model = Crmaccount
        fields = ('host', 'token',)

django/call_app/views.py
from django.shortcuts import render
from .models import Crmaccount, Call, Customer
from .forms import CrmaccountForm
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse
import json
import requests


AUTHORIZATION_TOKEN = 'Bearer NDFjNjE3ODJkYjg0MDhjNTMzMDlkNDg3ZjRlOGE5NTU2ODk0MmI3ZGRmYTAxYjU4MTgxMzkyMjZkOGJlNmFjOA'


def index(request):

    crmaccount_list = Crmaccount.objects.all()
    form = CrmaccountForm()

    # url = "https://webhook.site/988dd30f-da87-4136-b930-8e51c1de9adc"
    # response = requests.post(url, json={'msg': 'Hello world'})
    # response.json()
    return render(request, 'call_app/index.html', {'crmaccount_list': crmaccount_list, "form": form})
    # return HttpResponse("Index page")


@csrf_exempt
def deal_result(request):
    if request.method == 'GET':
        return HttpResponse("deal result page")
    elif request.method == 'POST':
        payload = json.loads(request.body)

        deal_id = payload['data']['deal']['Id']
        result = payload['data']['deal']['result']

        url = f"https://mp72700630.megaplan.ru/api/v3/deal/{deal_id}/"
        headers = {'Authorization': AUTHORIZATION_TOKEN}
        data = {"Category1000060CustomFieldRezultatZvonka": result}
        response = requests.post(url, headers=headers, json=data)
        return JsonResponse(response.json())


@csrf_exempt
def webhook_input(request):
    if request.method == "GET":
        return HttpResponse("webhook page")
    elif request.method == "POST":
        webhook = json.loads(request.body)
        deal_id = webhook['data']['deal']['Id']
    # def cart(deal_id):
        # url = f"https://mp72700630.megaplan.ru/api/v3/deal/{deal_id}/"
        # headers = {
        #   'Authorization': AUTHORIZATION_TOKEN
        # }
        # response = requests.get(url, headers=headers)
        # deal_data = response.json()
    with open('/django/call_app/megaplan/cart.json', 'rt') as f:
        data = json.load(f)
        tipe_of_deal = data['class']
        employee = data["data"]["deal"]["Category1000060CustomFieldVneshtatniySpetsialist"][0]["Name"]
        employee_number = data['data']["deal"]["Name"]
        customer_number = data["data"]["deal"]["Manager"]['phone']
        customer_surname = data['data']["deal"]["Contractor"]["Id"]

    customer = Customer(surname=customer_surname)
    customer.save()

    call = Call.objects.create(deal_id_megaplan=deal_id,
                               tipe_of_deal=tipe_of_deal, employee=employee,
                               customer=customer,
                               employee_number=employee_number,
                               customer_number=customer_number)
    data_ats = " id_звонка  " + str(call.id) + "\nсотрудник  " + str(employee_number) + "\nклиент  "\
                              + str(customer_number) + '\n'

    with open(f'/django/call_app/ats/{call.id}.txt', 'w') as f:
        f.write(data_ats)
    return JsonResponse({'deal_id': deal_id})


def calls(request):
    call_list = Call.objects.all()
    return render(request, 'call_app/calls.html', {'call_list': call_list})

django/call_app/templates/call_app/base.html
{% load static %}
<html lang="en">
      <head>
        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width">

        <title>Call</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/call_app.css' %}">
    </head>
    <body>


           {% block nav %}
           <div class="container-fluid p-0 "style="margin-left: 0px; margin-right: 0 px;">

           <nav class=" navigation navbar navbar-expand-lg navbar-light" style="background-color: #c7e7ed;">
           <a class="navbar-brand" href="{% url 'call_app:index' %}">Мегаплан</a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
               aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
           </button>


           <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
             <ul class="navbar-nav">

             <li class="nav-item">
               <a class="nav-link " href="#"> Контроль </a>
             </li>

             <li class="nav-item">
               <a class="nav-link" href="#">Сотрудники</a>
             </li>

             <li class="nav-item">
               <a class="nav-link" href="#">Клиенты</a>
             </li>

             <li class="nav-item">
               <a class="nav-link" href="{% url 'call_app:calls' %}">Звонки</a>

              <li class="nav-item">
               <a class="nav-link" href="#">Сделки</a>


             </ul>
            </div>
       </nav>
       </div>
            {% endblock %}




      {% block content %} {% endblock %}

      {% block pagination %}
      <div class="container-fluid">
      <nav aria-label="...">
          <ul class="pagination justify-content-center">

             <li class="page-item">
             {% if page_obj.has_previous %}
             <a href="?page={{ page_obj.previous_page_number }}">назад</a>
             {% endif %}
             </li>

              <li class="page-item">
              {% if page_obj.number == 1 %}
              <a  href="/all?page=1">1</a>  из {{ page_obj.paginator.num_pages }}

              {% else %}
              {{page_obj.number}} из {{ page_obj.paginator.num_pages }}
              {% endif %}
              </li>

              <li class="page-item">
             {% if page_obj.has_next %}
             <a href="?page={{ page_obj.next_page_number }}">далее</a>
             {% endif %}
              </li>


          </ul>
      </nav>

      {% endblock %}
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>

    </body>
  </html>

django/call_app/templates/call_app/calls.html
{% extends 'call_app/base.html' %}
{% block pagination %} {% endblock %}
{% block content %}


<div>


            <div class="call_app">
            <table  cellpadding="10" border="1" color: blue  width="70%">
              <tr style="background-color: #c7e7ed;">
              <th>Время звонка</th>
              <th>Тип звонка</th>
              <th>id_звонка</th>
              <th>Сотрудник</th>
              <th>Сделка</th>
              <th>Тип сделки</th>
              <th>Длительность разговора</th>
              <th>Ссылка на запись</th>
              <th>Результат звонка</th>
              <th>Добавлено в CRM</th>


              </tr>
            {% for call in call_list %}
                <tr>
                <td> </td>
                <td></td>
                <td>{{call.id}}</td>
                <td>{{call.employee}}</td>
                <td>{{call.deal_id_megaplan}}</td>
                <td>{{call.tipe_of_deal}}</td>
                <td>{{call.call_len}}</td>
                <td></td>
                <td>{{call.result}}</td>
                <td>{{call.in_crm}}</td>

                <tr>
            {% endfor %}

            </table>
            </div>

</div>
{% endblock %}

django/call_app/templates/call_app/index.html
{% extends 'call_app/base.html' %}
{% block pagination %} {% endblock %}
{% block content %}


<div>


            <div class="form">
            <form action="{% url 'call_app:index' %}" method="POST" >
                {% csrf_token %}

                       <table>
                          {{ form  }}
                       </table>
            <button type="button" class="btn btn-outline-info" >Проверить авторизацию</button>
            </form>

            </div>


            <div class="crmaccount">
            <table  cellpadding="10" border="1" width="50%">
              <tr style="background-color: #c7e7ed;">
              <th>NN</th>
              <th>CRM</th>
              <th>TOKEN</th>

              </tr>
            {% for crmaccount in crmaccount_list %}
                <tr>
                <td> {{ crmaccount.id }}</td>
                <td>{{ crmaccount.host }}</td>
                <td>{{crmaccount.token}}</td>
                <tr>
            {% endfor %}

            </table>
            </div>

</div>
{% endblock %}